name: Gradle cache
description: Gradle cache

runs:
  using: composite
  steps:
    - id: weekly-cache
      shell: bash
      run: echo "key=$(TZ=Asia/Tokyo date +%W)" >> $GITHUB_OUTPUT

    - uses: actions/cache@v4
      with:
        path: ~/.gradle/wrapper
        key: gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}

    - uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches/jars-*
          ~/.gradle/caches/transforms-*
          ~/.gradle/caches/modules-*
        key: gradle-dependencies-${{ steps.weekly-cache.outputs.key }}-${{ hashFiles('gradle/libs.versions.toml', '**/*.gradle.kts') }}
        restore-keys: gradle-dependencies-${{ steps.weekly-cache.outputs.key }}-

    - uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches/build-cache-*
          ~/.gradle/caches/[0-9]*.*
          .gradle
        key: ${{ runner.os }}-gradle-build-${{ github.workflow }}-${{ steps.weekly-cache.outputs.key }}-${{ github.sha }}
        restore-keys: ${{ runner.os }}-gradle-build-${{ github.workflow }}-${{ steps.weekly-cache.outputs.key }}-
